import "./globals.css";
import Navbar from "./components/Navbar/index";
import Footer from "./components/Footer/index";
import ScrollToTopButton from "./components/ScrollToTopButton";

export const metadata = {
  title: "create next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ScrollToTopButton />
        {children}
        <Footer />
      </body>
    </html>
  );
}
